name: renovate lint
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-latest
    name: renovate lint
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - uses: actions/setup-node@949feb2413d6458794dcd2491c4babbbce0c15c1 # v7.1.0

      - name: validate renovate config
        run: npx --package renovate -c renovate-config-validator
