name: renovate lint
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-latest
    name: renovate lint
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0

      - name: validate renovate config
        run: npx --package renovate -c renovate-config-validator
